<style>
    .nepPanLinks .sapMTB {
        border-bottom: none;
        margin-top: 20px;
    }

    .nepPanLogon {
        border-bottom: none;
        background-color: rgba(255, 255, 255, 0.9);
    }

    .sapUiTheme-sap_fiori_3_dark .nepPanLogon {
        background-color: rgba(0, 0, 0, 0.6);
    }

    .nepPanLogonBorder {
        border-radius: 15px;
    }

    .nepFlexPhone .sapMFlexItem {
        width: 100%;
        height: 100%;
    }
</style>